// Automagically generated by enummaker.exe.
// DO NOT EDIT THIS FILE (Yes, I mean you!)
#ifndef __glbdef_h__
#define __glbdef_h__

#include "mygba.h"
#include "rand.h"

// Definitions for ITEM
enum ITEM_NAMES
{
    ITEM_NONE,
    ITEM_SPEEDBOOTS,
    ITEM_QUICKBOOST,
    ITEM_BLIND,
    ITEM_SLOW,
    ITEM_REGENRING,
    ITEM_INVULNERABLE,
    ITEM_HEALPOTION,
    ITEM_MANAPOTION,
    ITEM_WEAPON,
    ITEM_SPELLBOOK,
    NUM_ITEMS
};

// Macros for ITEM
#define FOREACH_ITEM(x) \
    for ((x) = (ITEM_NAMES) 0; \
         (x) < NUM_ITEMS; \
         (x) = (ITEM_NAMES) ((int)(x)+1))

struct ITEM_DEF
{
    const char *name;
    const char *gaintxt;
    const char *losetxt;
    s16 timer;
    s16 rarity;
    u8 symbol;
    u8 attr;
    bool exclusive : 1;
    bool needtarget : 1;
    bool unstackable : 1;
};

extern const ITEM_DEF glb_itemdefs[];

// Definitions for BOOK_ELEMENT
enum BOOK_ELEMENT_NAMES
{
    BOOK_ELEMENT_SHOCK,
    BOOK_ELEMENT_LIGHTNING,
    BOOK_ELEMENT_THUNDER,
    BOOK_ELEMENT_CHILL,
    BOOK_ELEMENT_COLD,
    BOOK_ELEMENT_FROST,
    BOOK_ELEMENT_FIRE,
    BOOK_ELEMENT_POISON,
    BOOK_ELEMENT_FORCE,
    NUM_BOOK_ELEMENTS
};

// Macros for BOOK_ELEMENT
#define FOREACH_BOOK_ELEMENT(x) \
    for ((x) = (BOOK_ELEMENT_NAMES) 0; \
         (x) < NUM_BOOK_ELEMENTS; \
         (x) = (BOOK_ELEMENT_NAMES) ((int)(x)+1))

struct BOOK_ELEMENT_DEF
{
    const char *name;
    u8 area;
    u8 power;
    u8 consistency;
    u8 range;
    u8 mana;
    u8 attr;
};

extern const BOOK_ELEMENT_DEF glb_book_elementdefs[];

// Definitions for BOOK_MATERIAL
enum BOOK_MATERIAL_NAMES
{
    BOOK_MATERIAL_PAPYRUS,
    BOOK_MATERIAL_PAPER,
    BOOK_MATERIAL_LEATHER,
    BOOK_MATERIAL_METAL,
    BOOK_MATERIAL_GOLD,
    BOOK_MATERIAL_SKIN,
    BOOK_MATERIAL_DRAGONHIDE,
    BOOK_MATERIAL_NAUGAHYDE,
    NUM_BOOK_MATERIALS
};

// Macros for BOOK_MATERIAL
#define FOREACH_BOOK_MATERIAL(x) \
    for ((x) = (BOOK_MATERIAL_NAMES) 0; \
         (x) < NUM_BOOK_MATERIALS; \
         (x) = (BOOK_MATERIAL_NAMES) ((int)(x)+1))

struct BOOK_MATERIAL_DEF
{
    const char *name;
    u8 area;
    u8 power;
    u8 consistency;
    u8 range;
    u8 mana;
};

extern const BOOK_MATERIAL_DEF glb_book_materialdefs[];

// Definitions for BOOK_TYPE
enum BOOK_TYPE_NAMES
{
    BOOK_TYPE_BOLT,
    BOOK_TYPE_BALL,
    BOOK_TYPE_STORM,
    NUM_BOOK_TYPES
};

// Macros for BOOK_TYPE
#define FOREACH_BOOK_TYPE(x) \
    for ((x) = (BOOK_TYPE_NAMES) 0; \
         (x) < NUM_BOOK_TYPES; \
         (x) = (BOOK_TYPE_NAMES) ((int)(x)+1))

struct BOOK_TYPE_DEF
{
    const char *name;
    u8 area;
    u8 power;
    u8 consistency;
    u8 range;
    u8 mana;
    u8 symbol;
};

extern const BOOK_TYPE_DEF glb_book_typedefs[];

// Definitions for WEAPON_MODIFIER
enum WEAPON_MODIFIER_NAMES
{
    WEAPON_MODIFIER_BROKEN,
    WEAPON_MODIFIER_WORN,
    WEAPON_MODIFIER_CHIPPED,
    WEAPON_MODIFIER_SCRATCHED,
    WEAPON_MODIFIER_PLAIN,
    WEAPON_MODIFIER_SHARP,
    WEAPON_MODIFIER_HOMING,
    WEAPON_MODIFIER_RUNED,
    WEAPON_MODIFIER_GLOWING,
    WEAPON_MODIFIER_ELDRITCH,
    WEAPON_MODIFIER_ARTIFACT,
    NUM_WEAPON_MODIFIERS
};

// Macros for WEAPON_MODIFIER
#define FOREACH_WEAPON_MODIFIER(x) \
    for ((x) = (WEAPON_MODIFIER_NAMES) 0; \
         (x) < NUM_WEAPON_MODIFIERS; \
         (x) = (WEAPON_MODIFIER_NAMES) ((int)(x)+1))

struct WEAPON_MODIFIER_DEF
{
    const char *name;
    u8 power;
    u8 accuracy;
    u8 consistency;
};

extern const WEAPON_MODIFIER_DEF glb_weapon_modifierdefs[];

// Definitions for WEAPON_TYPE
enum WEAPON_TYPE_NAMES
{
    WEAPON_TYPE_KNIFE,
    WEAPON_TYPE_SHORTSWORD,
    WEAPON_TYPE_LONGSWORD,
    WEAPON_TYPE_AXE,
    WEAPON_TYPE_BATTLEAXE,
    WEAPON_TYPE_CLUB,
    WEAPON_TYPE_MACE,
    WEAPON_TYPE_HAMMER,
    WEAPON_TYPE_WARHAMMER,
    WEAPON_TYPE_DAGGER,
    WEAPON_TYPE_SHORTSPEAR,
    WEAPON_TYPE_SPEAR,
    NUM_WEAPON_TYPES
};

// Macros for WEAPON_TYPE
#define FOREACH_WEAPON_TYPE(x) \
    for ((x) = (WEAPON_TYPE_NAMES) 0; \
         (x) < NUM_WEAPON_TYPES; \
         (x) = (WEAPON_TYPE_NAMES) ((int)(x)+1))

struct WEAPON_TYPE_DEF
{
    const char *name;
    const char *verb;
    u8 power;
    u8 accuracy;
    u8 consistency;
};

extern const WEAPON_TYPE_DEF glb_weapon_typedefs[];

// Definitions for WEAPON_MATERIAL
enum WEAPON_MATERIAL_NAMES
{
    WEAPON_MATERIAL_WOOD,
    WEAPON_MATERIAL_STONE,
    WEAPON_MATERIAL_BRONZE,
    WEAPON_MATERIAL_IRON,
    WEAPON_MATERIAL_STEEL,
    WEAPON_MATERIAL_SILVER,
    WEAPON_MATERIAL_GOLD,
    WEAPON_MATERIAL_ADAMANTIUM,
    WEAPON_MATERIAL_UNOBTANIUM,
    WEAPON_MATERIAL_CRYSTAL,
    WEAPON_MATERIAL_ZIRCONIUM,
    WEAPON_MATERIAL_QUARTZ,
    WEAPON_MATERIAL_RUBY,
    WEAPON_MATERIAL_EMERALD,
    WEAPON_MATERIAL_DIAMOND,
    NUM_WEAPON_MATERIALS
};

// Macros for WEAPON_MATERIAL
#define FOREACH_WEAPON_MATERIAL(x) \
    for ((x) = (WEAPON_MATERIAL_NAMES) 0; \
         (x) < NUM_WEAPON_MATERIALS; \
         (x) = (WEAPON_MATERIAL_NAMES) ((int)(x)+1))

struct WEAPON_MATERIAL_DEF
{
    const char *name;
    u8 power;
    u8 accuracy;
    u8 consistency;
};

extern const WEAPON_MATERIAL_DEF glb_weapon_materialdefs[];

// Definitions for ROLE
enum ROLE_NAMES
{
    ROLE_BARBARIAN,
    ROLE_THIEF,
    ROLE_FIGHTER,
    ROLE_PALADIN,
    ROLE_TOURIST,
    ROLE_MONK,
    ROLE_PRIEST,
    ROLE_SHAMAN,
    ROLE_WIZARD,
    NUM_ROLES
};

// Macros for ROLE
#define FOREACH_ROLE(x) \
    for ((x) = (ROLE_NAMES) 0; \
         (x) < NUM_ROLES; \
         (x) = (ROLE_NAMES) ((int)(x)+1))

struct ROLE_DEF
{
    const char *name;
    u8 mp;
    u8 hp;
    u8 w_power;
    u8 w_accuracy;
    u8 w_consistency;
    u8 b_range;
    u8 b_power;
    u8 b_consistency;
    u8 b_area;
    u8 b_mana;
    u8 symbol;
};

extern const ROLE_DEF glb_roledefs[];

// Definitions for MOB
enum MOB_NAMES
{
    MOB_NONE,
    MOB_AVATAR,
    MOB_ANT,
    MOB_BAT,
    MOB_CAT,
    MOB_DOG,
    MOB_ECHIDNA,
    MOB_FROG,
    MOB_GHOST,
    MOB_HORSE,
    MOB_IMP,
    MOB_JACKRABBIT,
    MOB_KOBOLD,
    MOB_LICHEN,
    MOB_MOUSE,
    MOB_NEWT,
    MOB_ORC,
    MOB_PENGUIN,
    MOB_QUEENBEE,
    MOB_RAT,
    MOB_SNAKE,
    MOB_TURTLE,
    MOB_UNICORN,
    MOB_VAMPIRE,
    MOB_WARTHOG,
    MOB_GRIDBUG,
    MOB_YELLOWLIGHT,
    MOB_ZOMBIE,
    MOB_APE,
    MOB_BEAR,
    MOB_CENTAUR,
    MOB_DRAGON,
    MOB_ELEPHANT,
    MOB_FUNGUS,
    MOB_GIANT,
    MOB_HIPPO,
    MOB_ICEBEAST,
    MOB_JAGUAR,
    MOB_KLEPTOMANIAC,
    MOB_LICH,
    MOB_MUMMY,
    MOB_NAGA,
    MOB_OGRE,
    MOB_PYTHON,
    MOB_QUOLL,
    MOB_ROUS,
    MOB_SLUG,
    MOB_TROLL,
    MOB_UMBERHULK,
    MOB_VAMPIRELORD,
    MOB_WRAITH,
    MOB_XORN,
    MOB_YETI,
    MOB_SKELETONCAPTAIN,
    MOB_EVILDEMON,
    NUM_MOBS
};

// Macros for MOB
#define FOREACH_MOB(x) \
    for ((x) = (MOB_NAMES) 0; \
         (x) < NUM_MOBS; \
         (x) = (MOB_NAMES) ((int)(x)+1))

struct MOB_DEF
{
    const char *name;
    const char *melee_name;
    const char *melee_verb;
    DICE melee_damage;
    const char *range_name;
    const char *range_verb;
    DICE range_damage;
    u8 symbol;
    u8 attr;
    u8 melee_chance;
    u8 melee_item;
    u8 range_range;
    u8 range_symbol;
    u8 range_attr;
    u8 max_hp;
    u8 max_mp;
    u8 depth;
    u8 rarity;
    u8 ai;
    u8 sightrange;
    bool isfriendly : 1;
    bool range_valid : 1;
    bool isslow : 1;
    bool isfast : 1;
    bool isvampire : 1;
    bool hidefromlos : 1;
    bool isregenerate : 1;
    bool passwall : 1;
    bool candig : 1;
    bool swallows : 1;
    bool breeder : 1;
    bool isthief : 1;
    bool canleap : 1;
};

extern const MOB_DEF glb_mobdefs[];

// Definitions for AI
enum AI_NAMES
{
    AI_NONE,
    AI_STAYHOME,
    AI_HOME,
    AI_CHARGE,
    AI_STRAIGHTLINE,
    AI_PATHTO,
    AI_ORTHO,
    AI_FLANK,
    AI_RANGECOWARD,
    AI_COWARD,
    AI_MOUSE,
    NUM_AIS
};

// Macros for AI
#define FOREACH_AI(x) \
    for ((x) = (AI_NAMES) 0; \
         (x) < NUM_AIS; \
         (x) = (AI_NAMES) ((int)(x)+1))

// Definitions for TILE
enum TILE_NAMES
{
    TILE_INVALID,
    TILE_FLOOR,
    TILE_DOWNSTAIRS,
    TILE_UPSTAIRS,
    TILE_SNOWYPATH,
    TILE_PATH,
    TILE_GRASS,
    TILE_FIELD,
    TILE_FIRE,
    TILE_WALL,
    TILE_SOLIDWALL,
    TILE_PORTAL,
    TILE_ORANGEPORTAL,
    TILE_BLUEPORTAL,
    TILE_PROTOPORTAL,
    TILE_BROKENWALL,
    TILE_DOOR,
    TILE_MOUNTAIN,
    TILE_ICEMOUNTAIN,
    TILE_SNOWYPASS,
    TILE_BRIDGE,
    TILE_WATER,
    TILE_FOREST,
    NUM_TILES
};

// Macros for TILE
#define FOREACH_TILE(x) \
    for ((x) = (TILE_NAMES) 0; \
         (x) < NUM_TILES; \
         (x) = (TILE_NAMES) ((int)(x)+1))

struct TILE_DEF
{
    const char *legend;
    u8 symbol;
    u8 attr;
    bool ispassable : 1;
    bool istransparent : 1;
    bool isphaseable : 1;
    bool isdiggable : 1;
    bool roomcolor : 1;
};

extern const TILE_DEF glb_tiledefs[];

// Definitions for EVENTTYPE
enum EVENTTYPE_NAMES
{
    EVENTTYPE_NONE = 0,
    EVENTTYPE_FORE = 1,
    EVENTTYPE_BACK = 2,
    EVENTTYPE_SYM = 4,
    EVENTTYPE_FORESYM = 5,
    EVENTTYPE_FOREBACK = 3,
    EVENTTYPE_ALL = 7,
    NUM_EVENTTYPES
};

// Macros for EVENTTYPE
#define FOREACH_EVENTTYPE(x) \
    for ((x) = (EVENTTYPE_NAMES) 0; \
         (x) < NUM_EVENTTYPES; \
         (x) = (EVENTTYPE_NAMES) ((int)(x)+1))

// Definitions for MAPFLAG
enum MAPFLAG_NAMES
{
    MAPFLAG_NONE = 0,
    MAPFLAG_FOV = 1,
    MAPFLAG_FOVCACHE = 2,
    MAPFLAG_PORTAL = 4,
    MAPFLAG_DIST = 8,
    NUM_MAPFLAGS
};

// Macros for MAPFLAG
#define FOREACH_MAPFLAG(x) \
    for ((x) = (MAPFLAG_NAMES) 0; \
         (x) < NUM_MAPFLAGS; \
         (x) = (MAPFLAG_NAMES) ((int)(x)+1))

// Definitions for ATTR
enum ATTR_NAMES
{
    ATTR_NONE,
    ATTR_HEALTH,
    ATTR_MANA,
    ATTR_POWERBAR,
    ATTR_BORDER,
    ATTR_VICTORYBORDER,
    ATTR_DEATHBORDER,
    ATTR_DEATHBAR,
    ATTR_INVULNERABLE,
    ATTR_HILITE,
    ATTR_ELECTRICBLUE,
    ATTR_METAL,
    ATTR_BLUEPORTAL,
    ATTR_ORANGEPORTAL,
    ATTR_YELLOW,
    ATTR_PURPLE,
    ATTR_NORMAL,
    ATTR_LIGHTBLACK,
    ATTR_OUTOFFOV,
    ATTR_WHITE,
    ATTR_ORANGE,
    ATTR_BROWN,
    ATTR_RED,
    ATTR_DKRED,
    ATTR_GREEN,
    ATTR_DKGREEN,
    ATTR_BLUE,
    ATTR_CYAN,
    ATTR_GREY,
    NUM_ATTRS
};

// Macros for ATTR
#define FOREACH_ATTR(x) \
    for ((x) = (ATTR_NAMES) 0; \
         (x) < NUM_ATTRS; \
         (x) = (ATTR_NAMES) ((int)(x)+1))

struct ATTR_DEF
{
    u8 bg_r;
    u8 bg_g;
    u8 bg_b;
    u8 fg_r;
    u8 fg_g;
    u8 fg_b;
    bool pulse : 1;
};

extern const ATTR_DEF glb_attrdefs[];

// Definitions for ACTION
enum ACTION_NAMES
{
    ACTION_NONE,
    ACTION_RESTART,
    ACTION_BUMP,
    ACTION_FIRE,
    ACTION_ROTATE,
    ACTION_REBOOTAVATAR,
    ACTION_CHANGEROLE,
    ACTION_MANAPULSE,
    ACTION_DROP,
    ACTION_SUICIDE,
    NUM_ACTIONS
};

// Macros for ACTION
#define FOREACH_ACTION(x) \
    for ((x) = (ACTION_NAMES) 0; \
         (x) < NUM_ACTIONS; \
         (x) = (ACTION_NAMES) ((int)(x)+1))
#endif
